DROP TABLE IF EXISTS games CASCADE;

CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  date_played DATE NOT NULL,
  score INTEGER NOT NULL,
  win BOOLEAN DEFAULT FALSE,
  loss_level VARCHAR(255) NOT NULL,
  time_spent VARCHAR(255) NOT NULL
);